version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=db_TFM
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_TFM
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    private $host = "localhost"; // Nom del nostre servidor
    private $user = "root"; // Nom del nostre usuari
  